import Head from "next/head";
import { Inter } from "next/font/google";
import { useNavigate } from 'react-router-dom'
import { useRouter } from "next/router";
import 'bootstrap/dist/css/bootstrap.min.css'
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let router = useRouter()

  useEffect(()=>{
    router.push("/tasks");
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      </>
  );
}
