import Head from "next/head";
import { Inter } from "next/font/google";
import { useNavigate } from 'react-router-dom'
import 'bootstrap/dist/css/bootstrap.min.css'


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const navigate = useNavigate();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {navigate('/tasks/')}

      </>
  );
}
